### ISSUE TITLE
firing a context menu twice has unexpected behavior

### ISSUE THREAD

**Issue by mreinstein** [electerious/basicContext#10]
repro steps:

1 attach a context menu to an element
2 right click in the element
3 notice that the context menu appears as it should
4 right click again
5 notice that the context menu is still visible, and so is the built-in context menu (see attached screenshot.)

Expected behavior:
If you keep right clicking it will either toggle the visibility of the context menu or it will re-position it under the new mouse position

![screen shot 2015-07-06 at 12 08 17 pm](https://cloud.githubusercontent.com/assets/718067/8530750/be3da586-23d7-11e5-83b5-7f9b9d4e0833.png)

**Comment by electerious** [comment]
Repositioning wouldn't work, as the user may try to right-click on a different element, which isn't possible to detect. However, closing the modal sounds legit. Will add this in the future. Thanks for the suggestion.

**Comment by mreinstein** [comment]
but isnt the modal itself a singleton? I'd think when its opened it could have a state variable attached to it?

**Comment by electerious** [comment]
Context menus normally close when you left-click somewhere else. basicContext creates a transparent div in the background to imitate this behavior. When the user clicks the background, the context closes. I don't know if there's a way to get the element behind this div. This would be needed in order to open a new context based on where the user right-clicked.

**Comment by hellocosmin** [comment]
You don't really need the background div in order to close the menu. Just listen to a click event that happens outside the menu container, and hide it. For example: http://jsfiddle.net/SCSBB/22/

Using this approach, the background modal div wouldn't stand in the way and you could also detect if a different element was clicked.

With this, the behavior should be:

- attach context menu to item(s)
- click/right click any one of them: context menu opens
- click/right click:
  - outside of any basicContext-enabled element: context menu is removed
  - on a different element with basicContext enabled: close current menu, open the one on the just-clicked element
  - on the same element: context menu is repositioned

Thoughts?

**Comment by electerious** [comment]
@hellocosmin It would be a breaking change as it might produce a different behavior, but I welcome a PR. The idea sounds good!

**Comment by hellocosmin** [comment]
OK, forked it and I'll try to implement. Which branch should a PR target? v4.0.0, I suppose?

**Comment by electerious** [comment]
Both are semi-outdated. v4.0 is a complete rewrite, but I never finished it. Guess it's better to use master as the target.

**Comment by hellocosmin** [comment]
OK, got it working. Using a different approach than the one linked to above, hope it's OK.

It's my first PR ever, so please be gentle :)

**Comment by mreinstein** [comment]
@hellocosmin awesome! Thanks for taking this on and helping to fight the bitrot! 👍
